sudo: required
services:
  - docker

node_js:
  - "10.15.3"

before_install:
  - docker build -t craig-smith/docker-react -f Dockerfile.dev .

script:
  - docker run craig-smith/docker-react npm run test -- --coverage